### ISSUE TITLE
No Function named Degrain

### ISSUE THREAD

**Issue by ReclusiveEagle** [IFeelBloated/Plum#3]
Getting this error with Plum

Pum.py", line 225, in Basic
core                     = get_core()
File "C:\Users\Me\scripts\Plum.py", line 19, in __init__
self.MDegrainN     = vs.core.mvsf.Degrain
File "src\cython\vapoursynth.pyx", line 2413, in vapoursynth.Plugin.__getattr__
AttributeError: There is no function named Degrain

Degrain its self has several spaces. Instead of "self.MDegrainN     = vs.core.mvsf.Degrain"
Its currently "self.MDegrainN     = vs.core.mvsf.Degrain        " With 8 spaces at the end

But even fixing that doesn't do anything to solve the issue

**Comment by WolframRhodium** [comment]
The latest version of [mvsf](https://github.com/IFeelBloated/vapoursynth-mvtools-sf/releases/download/r10_pre/mvtools.dll) should be installed.
